name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          retry: 5
          run: |
            echo "count=${RETRY_RUN_ATTEMPT}" | tee -a "${GITHUB_OUTPUT}"
            test "${RETRY_RUN_ATTEMPT}" == 5

      - name: Test Local Action
        id: test-action-fail
        continue-on-error: true
        uses: ./
        with:
          retry: 3
          run: |
            echo "count=${RETRY_RUN_ATTEMPT}" | tee -a "${GITHUB_OUTPUT}"
            test "${RETRY_RUN_ATTEMPT}" == 5

      - name: Print Output
        id: output
        run: |
          echo "${{ toJson(steps.test-action.outputs) }}"

      - name: Test
        run: |
          test "${{ steps.test-action.outputs.count }}" == 5
          test "${{ steps.test-action-fail.outputs.count }}" == 3
          test "${{ steps.test-action-fail.outcome }}" == "failure"
